### ISSUE TITLE
Include the Scala logo

### ISSUE THREAD

**Issue by rgbkrk** [jove-sh/jove-scala#2]
If you put PNGs named "logo-32x32.png" and "logo-64x64.png" with the kernel spec (kernel.json), the Jupyter Notebook will pick up the logo for you!

**Comment by alexarchambault** [comment]
Thanks, that should be done, yes. The logos are already around (https://github.com/jove-sh/jove-scala/tree/master/src/main/resources/kernel/scala-2.11/resources, ...).

I'll do that for https://github.com/alexarchambault/jupyter-scala, which will supersedes my jove-* projects very soon.

**Comment by alexarchambault** [comment]
Fixed in https://github.com/alexarchambault/jupyter-scala:

![jove-scala 2](https://cloud.githubusercontent.com/assets/7063723/7656975/7eb355e0-fb2e-11e4-9da0-342f5cbdbd89.PNG)
